const restaurantData = [
    {
        id: 1,
        restaurantName: "Chaayos Chai+Snacks=Relax",
        restaurantImg: "https://placehold.co/400",
        cuisine: "Bakery, Beverages, Chaat, Desserts, Home Food, Italian, Maharashtrian, Snacks, Street Food, Sweets",
        rateing: 3.4,
        deliveryTime: "25-30 min",
        location: "Hinjawadi",
    },
    {
        id: 2,
        restaurantName: "McDonald's",
        restaurantImg: "https://placehold.co/400",
        cuisine: "Burgers, Beverages, Cafe, Desserts",
        rateing: 4.4,
        deliveryTime: "30-35 min",
        location: "Baner",
    },
    {
        id: 3,
        restaurantName: "Burger King",
        restaurantImg: "https://placehold.co/400",
        cuisine: "Burgers, American",
        rateing: 3.1,
        deliveryTime: "30-35 min",
        location: "Tathawade",
    },
    {
        id: 4,
        restaurantName: "Irani Cafe",
        restaurantImg: "https://placehold.co/400",
        cuisine: "Bakery, Snacks, Fast Food, Desserts, Beverages, Indian, Street Food",
        rateing: 4.8,
        deliveryTime: "35-40 min",
        location: "Baner",
    },
    {
        id: 5,
        restaurantName: "WarmOven Cake & Desserts",
        restaurantImg: "https://placehold.co/400",
        cuisine: "Bakery, Desserts, Ice Cream, Beverages",
        rateing: 4.1,
        deliveryTime: "30-35 min",
        location: "Wakad",
    },
    {
        id: 6,
        restaurantName: "Chaayos Chai+Snacks=Relax",
        restaurantImg: "https://placehold.co/400",
        cuisine: "Bakery, Beverages, Chaat, Desserts, Home Food, Italian, Maharashtrian, Snacks, Street Food, Sweets",
        rateing: 4.4,
        deliveryTime: "25-30 min",
        location: "Hinjawadi",
    },
    {
        id: 7,
        restaurantName: "McDonald's",
        restaurantImg: "https://placehold.co/400",
        cuisine: "Burgers, Beverages, Cafe, Desserts",
        rateing: 4.4,
        deliveryTime: "30-35 min",
        location: "Baner",
    },
    {
        id: 8,
        restaurantName: "Burger King",
        restaurantImg: "https://placehold.co/400",
        cuisine: "Burgers, American",
        rateing: 4.1,
        deliveryTime: "30-35 min",
        location: "Tathawade",
    },
    {
        id: 9,
        restaurantName: "Irani Cafe",
        restaurantImg: "https://placehold.co/400",
        cuisine: "Bakery, Snacks, Fast Food, Desserts, Beverages, Indian, Street Food",
        rateing: 4.1,
        deliveryTime: "35-40 min",
        location: "Baner",
    },
    {
        id: 10,
        restaurantName: "WarmOven Cake & Desserts",
        restaurantImg: "https://placehold.co/400",
        cuisine: "Bakery, Desserts, Ice Cream, Beverages",
        rateing: 4.1,
        deliveryTime: "30-35 min",
        location: "Wakad",
    }
]

export default restaurantData;